name: assets_audio_player
description: assets_audio_player containing the mobile and web libraries.
version: 3.1.1

dependencies:
  assets_audio_player
    path: assets_audio_player
  assets_audio_player_web
    path: assets_audio_player_web
